spring.application.name=sharenotes

spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USER}
spring.datasource.password=${SUPABASE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

# Flyway activation (auto-config disabled; Flyway bean defined manually in FlywayConfig.java)
spring.flyway.enabled=false